### ISSUE TITLE
代码块在列表中并且存在空行时会解析异常

### ISSUE THREAD

**Issue by 502647092** [ustc-zzzz/mcbbs-markdown2bbcode-converter#11]
如下代码
```
- abc
```yaml
#配置文件版本 请勿修改
Version: 1.2

#绑定标签处理
#检查操作 检索所有标签
#绑定操作 使用第一个标签
Tag:
  Bind:
  - '§6喵式绑定'
  - '§6灵魂绑定'
  - '§6SoulBound'
  # 时间绑定的标签
  TimeBind:
  - '§6到期时间'
.```
- def
```
复制的时候去掉最后三个 ``` 前面的 `.`

---

在没有空行的时候结果是正常的
```
[size=16px][list]
[*]abc[code]#配置文件版本 请勿修改
Version: 1.2
#绑定标签处理
#检查操作 检索所有标签
#绑定操作 使用第一个标签
Tag:
Bind:
- '§6喵式绑定'
- '§6灵魂绑定'
- '§6SoulBound'
# 时间绑定的标签
TimeBind:
- '§6到期时间'[/code]
[*]def[/list][/size]
```
有空行的时候 结果就变了

```
[size=16px][list]
[*]abc[code]#配置文件版本 请勿修改
Version: 1.2
[/code][/list][/size]
[size=16px]#绑定标签处理 #检查操作 检索所有标签 #绑定操作 使用第一个标签 Tag:   Bind:[/size]

[size=16px][list]
[*]'§6喵式绑定'
[*]'§6灵魂绑定'
[*]'§6SoulBound'[size=32px][b]时间绑定的标签[/b][/size]

TimeBind:
[*]'§6到期时间'
```[size=16px][list]
[*]def[/list][/size][/list][/size]
```
